court_case clean_case_number
AyOK-Code/oscn pull request #199
Opened 2023-08-22 20:25 UTC by AspiringDev51

2023-08-28 17:57 UTC, sgelbart reviewed
we also need for crf_number

2023-08-28 18:01 UTC, sgelbart commented on db/migrate/20230822190043_add_clean_case_number_to_court_cases.rb
> +    END"
you need the add_column statement

2023-08-28 18:02 UTC, sgelbart reviewed
also need on doc_sentences for the crf_number

2023-08-29 19:33 UTC, holdenmitchell requested changes
Thanks for getting this started. A couple of comments:

1) I really don't think we need a generated column on the `court_cases` table since that is the format that we are trying to match to. I'm open to changing my mind if you/Sabrina can send me some examples of case numbers that need to be cleaned from OSCN.

2) There are a lot of big changes to your schema file in this PR that don't have anything to do with the current work. You might try dropping the database and regenerating the database? Or revert the changes and use `git add db/schema.rb --patch`.

2023-08-29 19:33 UTC, holdenmitchell commented on db/migrate/20230822190043_add_clean_case_number_to_court_cases.rb
> +class AddCleanCaseNumberToCourtCases < ActiveRecord::Migration[7.0]
I really don't think that we need clean case number on the `court_cases` table. If you can find some examples, I'm open to it, but in my mind the clean case number column is getting the case number into the OSCN format

2023-08-29 19:33 UTC, holdenmitchell commented on db/migrate/20230829151652_add_clean_case_number_to_doc_sentences.rb
> +end
Strange spacing. Do you have a linter installed?

2023-08-29 19:33 UTC, holdenmitchell commented on db/schema.rb
> +
This is a big schema change that is not related to this PR. Let's drop this so that our schema file stays clean 🧹

2023-08-29 19:33 UTC, holdenmitchell commented on db/schema.rb
> +
Same as above:

> This is a big schema change that is not related to this PR. Let's drop this so that our schema file stays clean 🧹

2023-08-29 19:33 UTC, holdenmitchell commented on db/schema.rb
> +
Not sure what is going on here...

2023-08-29 19:33 UTC, holdenmitchell commented on db/schema.rb
> +
This is a big schema change that is not related to this PR. Let's drop this so that our schema file stays clean 🧹

2023-08-29 19:33 UTC, holdenmitchell commented on db/schema.rb
> +
This is a big schema change that is not related to this PR. Let's drop this so that our schema file stays clean 🧹

2023-08-29 19:33 UTC, holdenmitchell commented on db/schema.rb
> +
This is a big schema change that is not related to this PR. Let's drop this so that our schema file stays clean 🧹

2023-08-29 19:33 UTC, holdenmitchell commented on db/schema.rb
> +  add_foreign_key "authtoken_token", "auth_user", column: "user_id", name: "authtoken_token_user_id_35299eff_fk_auth_user_id", deferrable: :deferred
This is a big schema change that is not related to this PR. Let's drop this so that our schema file stays clean 🧹

2023-08-29 19:33 UTC, holdenmitchell commented on db/schema.rb
> +  add_foreign_key "django_celery_beat_periodictask", "django_celery_beat_solarschedule", column: "solar_id", name: "django_celery_beat_p_solar_id_a87ce72c_fk_django_ce", deferrable: :deferred
This is a big schema change that is not related to this PR. Let's drop this so that our schema file stays clean 🧹

2023-08-29 19:33 UTC, holdenmitchell commented on db/schema.rb
> +  add_foreign_key "socialaccount_socialtoken", "socialaccount_socialapp", column: "app_id", name: "socialaccount_social_app_id_636a42d7_fk_socialacc", deferrable: :deferred
This is a big schema change that is not related to this PR. Let's drop this so that our schema file stays clean 🧹

2024-07-09 12:58 UTC, holdenmitchell commented
Closing due to the number of changes that are unrelated to this PR. I will re-open a PR for just the DOC Clean case number

2024-07-09 12:58 UTC, closed without merging