tables created and migrated
AyOK-Code/oscn pull request #219
Opened 2023-12-04 19:24 UTC by AspiringDev51

2023-12-08 18:00 UTC, holdenmitchell requested changes
A couple of small tweaks 🔧

2023-12-08 18:00 UTC, holdenmitchell commented on spec/models/structure_fire_link_spec.rb
> +RSpec.describe StructureFireLink, type: :model do
Update spec based on the model changes

2023-12-08 18:06 UTC, AspiringDev51 commented on db/schema.rb
> +    t.date "date"
pdf_date_on

2023-12-15 17:26 UTC, holdenmitchell approved these changes
Looks good 🚒 🔥

2023-12-15 17:26 UTC, merged