Census Importer
AyOK-Code/oscn pull request #247
Opened 2024-05-28 22:41 UTC by sgelbart

2024-05-29 14:40 UTC, sgelbart commented on app/models/census/statistic.rb
> +  has_many :datas, class_name: 'Census::Data', dependent: :destroy
can maybe call something else...

2024-05-29 14:53 UTC, sgelbart commented on app/services/importers/census/import.rb
> +      end
these methods are a bit long...(sorry I'm back in python land)
let me know if you want me to shorten

2024-05-29 16:45 UTC, sgelbart commented on db/migrate/20240526172112_create_census_data.rb
> +      t.string :amount
I'm not sure about being a string
It looks like only 10 variables come is as strings from the census and it's "Median year". I'm not sure why a year would be a string and not an int...
it's easy enough to cast for now though and then we can do an analysis for any weird values that might warrant us keeping it a string and convert the column back later.

2024-06-03 22:21 UTC, sgelbart commented on app/services/scrapers/parties/low_priority.rb
Rubo....

2024-06-17 19:23 UTC, holdenmitchell requested changes
A couple of small code changes but for the most part it looks good! Could you also provide some sort of example script or rake task of how to pull this data into the database? I'm not super familiar with the Census data, so I'm not sure what order to run the imports and what params I should be using

One more question, how are is the zip codes table being seeded? Should there be something in the `db/seeds.rb` file or a one-off rake task?

2024-06-17 19:56 UTC, sgelbart commented
@holdenmitchell regarding zips - they're currently created using upsert. I did it this way because I planned on using the wildcard * to pull in all zips for whole counties at a time, in which case that table would just be self populating based on whichever counties Austin wanted zip data for long term. That list is also zip code tabulations (not exact zip codes). 

I didn't use the wildcard in the end so I just have the list of OKC zips hardcoded as a constant (ZipCode:LZIPS_OKLAHOMA_COUNTY). It's not much harder to add the wildcard functionality, or I could add a column for counties and seed the DB with that, or both, whatever you prefer.

Also added a sample call to the PR. There's sample code in the import_spec.rb file as well (not the clearest spot). Can add to the readme too if you want.

2024-06-18 18:45 UTC, holdenmitchell commented
@sgelbart Thanks! I will get this merged in after I run a couple of imports

2024-06-18 19:41 UTC, holdenmitchell approved these changes

2024-06-18 19:41 UTC, merged