Issue 81 district attorney
AyOK-Code/oscn pull request #84
Opened 2022-07-18 16:54 UTC by AspiringDev51

2022-07-21 12:03 UTC, holdenmitchell requested changes
Looking good! I mostly just reviewed the code on this first pass. If you could add some instructions of the various things I should test and be looking for in the PR description, that would help me know what to run in the console and check for in the database!

2022-07-21 12:03 UTC, holdenmitchell commented on spec/services/scrapers/district_attorney_spec.rb
> +      expect(DistrictAttorney.all.first.name).to eq data.first[:district_attorney]
Similar to the first expect comment. I think that using `.first` in a database call could make this test flaky in the future. My preference would be explicitly defining the district attorney that we are looking for

2022-07-21 16:26 UTC, AspiringDev51 commented on spec/examples.txt
> +example_id                                                 | status  | run_time        |
yea, don't know how, will delete .

2022-07-21 16:33 UTC, AspiringDev51 commented on lib/tasks/one-off/district_attorney.rake
> +    # By load, do you mean loading them into the database(saving) or returning them to the console?
ran the task, think I completed this successfully

2022-07-21 16:49 UTC, AspiringDev51 commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2022_07_19_193932) do
so when making my new PR to add these changes i use `git add db/schema.rb --patch` instead of git add .  ?

2022-08-03 15:38 UTC, holdenmitchell requested changes
Small change suggestion for the test and then this looks good to go!

2022-08-03 15:38 UTC, holdenmitchell commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2022_07_19_193932) do
Yea, you just want to make sure that you don't commit changes that are unrelated to the PR

2022-08-03 15:38 UTC, holdenmitchell commented on spec/services/scrapers/district_attorney_spec.rb
> +      create(:county, name: 'Tillman')
@AspiringDev51 I still think that this should be a change before deployment:

```ruby
counties = ['Beaver', 'Cimarron', 'Harper', 'Texas', 'Beckham', 'Custer', 'Ellis', 'Roger Mills', 'Washita', 'Greer', 'Harmon', 'Jackson', 'Kiowa', 'Tillman']

counties.each do |name|
  create(:county, name: name)
end
```

2022-08-03 17:26 UTC, AspiringDev51 commented on db/schema.rb
> +ActiveRecord::Schema.define(version: 2022_07_19_193932) do
Sabrina Helped me with this today.Think this is done

2022-08-03 22:09 UTC, holdenmitchell approved these changes
Looks good! 👍

2022-08-03 22:09 UTC, merged